import Head from 'next/head'
import { Inter } from 'next/font/google'

import { FormEvent, useState } from 'react'

import styles from '@checklist/styles/Home.module.css'
import LeftPane from '@checklist/components/LeftPane'
import RightPane from '@checklist/components/RightPane'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [todoText, setTodoText] = useState('');
  const [toDos, setToDos] = useState<AddedToDos[]>([]);

  function handleAddClick(){
    const currentToDos = [...toDos];
    currentToDos.push({ isCompleted: false, todoText })
    setToDos(currentToDos);
    setTodoText('');
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2>TODO Application</h2>
        <div className={styles.container}>
          <LeftPane
           onTODOTextChange={setTodoText}
           isDisabled={!todoText}
           onAddClickHandler={handleAddClick}
           todoText={todoText}/>
          <RightPane 
          addedToDos={toDos} />
        </div>
      </main>
    </>
  )
}

interface AddedToDos {
  isCompleted: boolean,
  todoText: string,
}